### ISSUE TITLE
jmespath.types not accessible

### ISSUE THREAD

**Issue by nicmendoza** [daz-is/jmespath-plus#3]
My assumption is this project is meant to offer a superset of the features of your original jmespath fork. I am trying to decorate jmespath as documented in the other fork, and the `types` property is not exposed on the jmespath object.

I was able to work around this by installing `@daz-is/jmespath` alongside this module and leveraging the `types` property exposed there, but that seems heavy-handed.

**Comment by darrenmothersele** [comment]
Thanks for spotting that, Nic.

I've just pushed 0.1.3 which fixes this.
